export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTISTS_ALL = 'GET_ARTISTS_ALL'
export const GET_ARTISTS_DETAIL = 'GET_ARTISTS_DETAIL'
export const CLEAR_ARTIST_DETAIL = 'CLEAR_ARTIST_DETAIL'


export const DARK_THEME = "DARK_THEME"